# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8e0ff322c6e24bb2db97a68bc3c2c35fc159967ecf9c45497098802c9e9017d21fc240aa31d9af83b2de62da5480572dbaec18d500235f76acf48a6eac7d6a1

test:
  secret_key_base: 6d586565fd5256009e66675b3cdb8c879a5f6c0a209e357d58c8a07a6b0e68b4bb312fe97e12a44675cf8879acf8abb5bc710e701a7dde321f3f22194d173ce3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
