# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04bfeae46b35bb479754ff1b6a8e5de6cb5c1be8a43de73f74e380c3c1c1d034181fa5d717331faeac9b47357e9baf94c99fa62a70855ebd0054b113db9f89f5

test:
  secret_key_base: a7a7c573c904bdad78712b2262cb141b4db371f7e7673489d0d8ce036d1757f4015e4c0a803db40b36a84c7b4d373379df7f6d32343191718f11eaa7a4199856

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
